title: Tulip4attoo's Blog
description: A blog about data analytics.

url: http://tulip4attoo.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: Pandoc
highlighter: pygments
paginate: 5

gems:
  - jekyll-pandoc

pandoc:
  extensions:
    - normalize
    - smart
    - mathjax
    - csl: _styles/apa.csl
    - bibliography: bibliography/references.bib

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
    github: Tulip4attoo
    twitter: 
    facebook: huylinh.nguyen
    email: huylinh.nguyen@outlook.com

google_analytics: 
