# Site settings
title: 生命不止，折腾不息
author: MonsterSlayer
author_avatar: /images/header.jpg
email: alias@domain.tld
description: 生命不止，折腾不息 
url: "https://dongyadoit.com"
domain: "http://dongyadoit.com"
github_username: dongyado
github_site_repo: dongyado/dongyado.github.io
disqus: monsterslayer

# MathJax configuration
mathjax: true
markdown: kramdown
kramdown:
    math_engine: mathjax
    syntax_highlighter: rouge
    extensions: ["fenced_code_blocks", "autolink", "tables", "smart"]

# Build settings
highlighter: rouge
sass:
    style: :compressed
    sass_dir: _sass

permalink: /:title/
excerpt_separator: "<!-- more -->"

# path
categories_path: categories/
tags_path: tags/

gems:
  - jekyll-sitemap
