title: Hello, world! I'm Tulip4attoo
description: > # this means to ignore newlines until "baseurl:"
  My technical blog. I will talk about many things 
  that not so-much personal here.
permalink: 'blog/:title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tulip4attoo.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Tulip4attoo 
author-img: tulip4attoo.jpg 
about-author: Gamer, Reader, Dreamer
facebook: huylinh.nguyen
github: Tulip4attoo
linkedin: # add your Linkedin handle
email: huylinh.nguyen@outlook.com

# Disqus
discus-identifier: tulip4attoo-github-io 

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
highlighter: rouge
# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090

plugins:
  - jekyll-sitemap
  - jekyll-paginate

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

paginate: 100
paginate_path: "blog/page:num/"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
