title: Tulip4attoo's Blog
description: My blog about data analytics, data visualization,... all about data.

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: Tulip4attoo
   twitter: 
   facebook: huylinh.nguyen
   email: huylinh.nguyen@outlook.com

google_analytics: "UA-58263416-1"
