# [NOTE] change this to your site name
site_name: Blog Template
# [NOTE] change this to your site url
site_url: https://tulip4attoo.github.io/


# [NOTE] edit mkdocs configs as normal
theme:
  name: 'material'

plugins:
  - blogging:
      dirs:
        - blog

      features:
        tags:
          index_page: tags.md
          insert: top
